server:
  port: 8082

spring:
  datasource:
    url: jdbc:h2:mem:test
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.H2Dialect
      jdbc:
        lob.non-contextual-creation: true
    properties:
      hibernate:
        show_sql: true
  output:
    ansi:
      enabled: Always


logging:
  level:
    com.ead: TRACE
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate: INFO

ead:
  api:
    url:
      authUser: 'http://ead-authuser-service'

eureka:
  client:
    service-url:
      defaultZone:  ${EUREKA_URL:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true