server:
  port: 8080

spring:
  application:
    name: ead-curse-service
  datasource:
    url: jdbc:postgresql://host.docker.internal:5432/ead-curse
    username: postgres
    password: mysecretpassword
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        lob.non-contextual-creation: true
    properties:
      hibernate:
        show_sql: true
  output:
    ansi:
      enabled: Always


logging:
  level:
    com.ead: TRACE
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate: INFO

ead:
  api:
    url:
      authUser: 'http://ead-authuser-service/ead-authuser'

eureka:
  client:
    service-url:
      defaultZone:  ${EUREKA_URL:http://172.18.224.1:8761/eureka}
  instance:
    prefer-ip-address: true